### ISSUE TITLE
Create a Python environment and Django project

### ISSUE THREAD

**Issue by rkeytech** [rkeytech/eve-industrialist#2]

**Comment by rkeytech** [comment]
### Tasks
- [ ] Create a python `3.9` virtual environment
- [ ] Install the required libraries for the project
- [ ] Create a `requirements.txt` file for the dependecies
- [ ] Create a Django project to work on
